VED KHEDAKR

In [2]:
import scipy.stats as stats
import statsmodels.api as sm
import numpy as np
import pandas as pd
     

In [3]:
buyer = pd.read_csv("BuyerRatio.csv")
buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
table = [[50,142,131,70],
        [435,1523,1356,750]]

In [5]:
stat, p, dof, exp = stats.chi2_contingency(table) 
print(stat,"\n", p,"\n", dof,"\n", exp)
     

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [6]:
stats.chi2_contingency(table) 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [7]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [8]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [9]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))

Significnace=0.050, p=0.810
